### ISSUE TITLE
Can I change the sidebar line-height of text back?

### ISSUE THREAD

**Issue by nanxiaobei** [SerafimArts/RoboticketLight#5]
Just use the IDE default `line-height` for sidebar items.

**Comment by SerafimArts** [comment]
This is not a mistake, it’s done on purpose. 

On laptops (where everything is small) and large screens (4k+ PC), the standard size is either not visible (because everything is small) or not visible (because the screen is large).

In this regard, to control and select something with the mouse is not convenient. The size is selected just on the basis of these tasks. That there were no problems on most devices.

![image](https://user-images.githubusercontent.com/2461257/85146270-35564800-b256-11ea-83f8-e61898ec6a44.png)

You can fork this repository and customize anything you want.

There is no any another settings in IDEA: https://www.jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes_customize.html

**Comment by SerafimArts** [comment]
issue closed due to lack of feedback
